markdown: kramdown
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/site/page:num/"

excerpt_separator: "\n\n\n"

title: Sydney Maples
email: smaples@stanford.edu
url: "http://sydneymaples.com"

future: true