markdown: kramdown
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/site/page:num/"

excerpt_separator: "\n\n\n"

title: Sydney Maples
email: smaples@stanford.edu
url: "http://sydneymaples.com"

collections:
  - lists

defaults:
  - 
    scope:
      path: "lists"
      type: "lists"
    values:
      layout: "list"

future: true